# **Features engineering**

In [1]:
# Import libraries
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
# Loading the data
input_path = Path("..") / 'data' / 'interim' / 'df_full_cleaned.csv'
df = pd.read_csv(input_path)
display(df.head(5))
print("Shape of the piezometer dataframe:\n", df.shape)

,date_index,code_bss,bss_id,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,precipitation_sum,shortwave_radiation_sum,et0_fao_evapotranspiration,cloud_cover_mean,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean
0,2017-01-01,10906X0039/C2-1,BSS002MNYD,101.85,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-01T07:19,2017-01-01T16:26,32800.70,0.0,7.88,0.95,47,1024.5,5.3,0.244,9.2
1,2017-01-02,10906X0039/C2-1,BSS002MNYD,101.89,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-02T07:19,2017-01-02T16:27,32850.58,0.0,4.29,0.56,93,1022.0,4.6,0.244,9.2
2,2017-01-03,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-03T07:19,2017-01-03T16:28,32904.28,0.0,8.02,1.59,3,1023.5,11.8,0.244,8.9
3,2017-01-04,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-04T07:19,2017-01-04T16:29,32961.75,0.0,8.08,2.52,5,1022.9,25.2,0.244,8.8
4,2017-01-05,10906X0039/C2-1,BSS002MNYD,102.01,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-05T07:19,2017-01-05T16:30,33022.91,0.0,6.93,2.07,14,1026.5,30.5,0.243,8.7

Shape of the piezometer dataframe:
 (2885, 19)

In [3]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['date_index', 'code_bss', 'bss_id', 'niveau_nappe_eau',
       'mode_obtention', 'nom_producteur', 'latitude', 'longitude', 'sunrise',
       'sunset', 'daylight_duration', 'precipitation_sum',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration',
       'cloud_cover_mean', 'pressure_msl_mean', 'wind_speed_10m_mean',
       'soil_moisture_0_to_100cm_mean', 'soil_temperature_0_to_100cm_mean'],
      dtype='str')>

In [4]:
# Index define as date_index
df = df.set_index('date_index')
display(df.head(5))

,code_bss,bss_id,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,precipitation_sum,shortwave_radiation_sum,et0_fao_evapotranspiration,cloud_cover_mean,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean
date_index,,,,,,,,,,,,,,,,,,
2017-01-01,10906X0039/C2-1,BSS002MNYD,101.85,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-01T07:19,2017-01-01T16:26,32800.70,0.0,7.88,0.95,47,1024.5,5.3,0.244,9.2
2017-01-02,10906X0039/C2-1,BSS002MNYD,101.89,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-02T07:19,2017-01-02T16:27,32850.58,0.0,4.29,0.56,93,1022.0,4.6,0.244,9.2
2017-01-03,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-03T07:19,2017-01-03T16:28,32904.28,0.0,8.02,1.59,3,1023.5,11.8,0.244,8.9
2017-01-04,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-04T07:19,2017-01-04T16:29,32961.75,0.0,8.08,2.52,5,1022.9,25.2,0.244,8.8
2017-01-05,10906X0039/C2-1,BSS002MNYD,102.01,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-05T07:19,2017-01-05T16:30,33022.91,0.0,6.93,2.07,14,1026.5,30.5,0.243,8.7

In [5]:
df.isna().sum()

code_bss                            0
bss_id                              0
niveau_nappe_eau                    0
mode_obtention                      0
nom_producteur                      0
latitude                            0
longitude                           0
sunrise                             0
sunset                              0
daylight_duration                   0
precipitation_sum                   0
shortwave_radiation_sum             0
et0_fao_evapotranspiration          0
cloud_cover_mean                    0
pressure_msl_mean                   0
wind_speed_10m_mean                 0
soil_moisture_0_to_100cm_mean       0
soil_temperature_0_to_100cm_mean    0
dtype: int64

In [6]:
# Shows duplicated rows for a date
print("Duplicated dates: ", df.index.duplicated().sum())
df[df.index.duplicated(keep=False)].sort_index()

# Keep only one reading per day (
df = df[~df.index.duplicated(keep="first")]

# Check for actual date gaps
inferred = pd.infer_freq(df.index)
print("Detected frequency: ", inferred)  # should print 'D' if perfectly daily and gap-free
full_range = pd.date_range(df.index.min(), df.index.max(), freq="D")
missing_dates = full_range.difference(df.index)
print("Missing dates: ",len(missing_dates))
print(missing_dates[:37])

Duplicated dates:  0
Detected frequency:  None
Missing dates:  2922
DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
               '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16',
               '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20',
               '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24',
               '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28',
               '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01',
               '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05',
               '2017-02-06'],
              dtype='datetime64[us]', freq='D')

In [7]:
# Confirm series.index.freq prints 'D' 
series = df["niveau_nappe_eau"].sort_index().asfreq("D").interpolate()

print("Detected frequency: ",series.index.freq)     # should now print 'D'
print("Na dates: ", series.isna().sum())   # should be 0
missing_dates = full_range.difference(series.index)
print("Missing dates: ",len(missing_dates))
print(missing_dates[:10])

Detected frequency:  <Day>
Na dates:  2922
Missing dates:  0
DatetimeIndex([], dtype='datetime64[us]', freq='D')

# Feature engineering

In [8]:
df.columns.tolist()

['code_bss',
 'bss_id',
 'niveau_nappe_eau',
 'mode_obtention',
 'nom_producteur',
 'latitude',
 'longitude',
 'sunrise',
 'sunset',
 'daylight_duration',
 'precipitation_sum',
 'shortwave_radiation_sum',
 'et0_fao_evapotranspiration',
 'cloud_cover_mean',
 'pressure_msl_mean',
 'wind_speed_10m_mean',
 'soil_moisture_0_to_100cm_mean',
 'soil_temperature_0_to_100cm_mean']

In [9]:
# Computation of the cumulative precipitation during the 7-30-90 last days
def cumulative_precipitation(df, days: int) -> pd.DataFrame:
    """
    Computation of the cumulative precipitation during the last 7-30-90 days
    """
    df[f'P_cum_{days}d'] = df['precipitation_sum'].rolling(window=days).sum()
    return df

def cumulative_eff_precipitation(df, days: int) -> pd.DataFrame:
    """
    Computation of the cumulative precipitation during the last 7-30-90 days minus 
    the et0_fao_evapotranspiration (mining the evaporation)
    """
    df[f'Peff_cum_{days}d'] = (df['precipitation_sum'] - df['et0_fao_evapotranspiration']).rolling(window=days).sum()
    return df

In [10]:
cumulative_precipitation(df, days = 7)
cumulative_precipitation(df, days = 30)
cumulative_precipitation(df, days = 90)
cumulative_eff_precipitation(df, days = 30)
cumulative_eff_precipitation(df, days = 90)
display(df.tail(10))

,code_bss,bss_id,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,...,cloud_cover_mean,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean,P_cum_7d,P_cum_30d,P_cum_90d,Peff_cum_30d,Peff_cum_90d
date_index,,,,,,,,,,,,,,,,,,,,,
2024-12-22,10906X0039/C2-1,BSS002MNYD,101.33,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-22T07:17,2024-12-22T16:19,32529.02,...,89,1020.8,25.4,0.169,10.6,16.6,53.5,174.6,15.87,19.93
2024-12-23,10906X0039/C2-1,BSS002MNYD,101.33,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-23T07:17,2024-12-23T16:19,32537.12,...,60,1024.1,37.4,0.167,10.3,16.7,53.6,173.1,14.94,18.65
2024-12-24,10906X0039/C2-1,BSS002MNYD,101.32,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-24T07:17,2024-12-24T16:20,32549.59,...,90,1025.4,33.4,0.165,10.3,17.1,54.2,173.7,15.14,20.73
2024-12-25,10906X0039/C2-1,BSS002MNYD,101.34,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-25T07:18,2024-12-25T16:20,32566.38,...,31,1029.2,16.4,0.162,10.8,17.1,53.4,173.7,14.51,22.48
2024-12-26,10906X0039/C2-1,BSS002MNYD,101.36,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-26T07:18,2024-12-26T16:21,32587.44,...,46,1030.9,4.0,0.161,10.3,13.8,53.4,173.4,15.01,23.92
2024-12-27,10906X0039/C2-1,BSS002MNYD,101.37,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-27T07:18,2024-12-27T16:22,32612.72,...,12,1031.8,5.3,0.163,9.8,13.4,53.4,173.4,15.38,27.21
2024-12-28,10906X0039/C2-1,BSS002MNYD,101.36,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-28T07:19,2024-12-28T16:23,32642.18,...,2,1029.5,6.3,0.162,9.0,6.7,53.4,173.4,15.62,29.17
2024-12-29,10906X0039/C2-1,BSS002MNYD,101.36,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-29T07:19,2024-12-29T16:23,32675.76,...,2,1028.9,7.8,0.158,8.5,0.7,53.4,173.4,15.41,30.67
2024-12-30,10906X0039/C2-1,BSS002MNYD,101.37,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-30T07:19,2024-12-30T16:24,32713.41,...,28,1030.5,4.2,0.155,8.3,0.6,53.4,173.4,15.69,32.16
2024-12-31,10906X0039/C2-1,BSS002MNYD,101.40,Valeur mesurée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2024-12-31T07:19,2024-12-31T16:25,32755.07,...,95,1032.3,5.1,0.155,8.3,0.3,52.9,152.6,15.50,12.10