### Stations

In [1]:
import requests
import pandas as pd

url = "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations"
params = {"size": 5000, "code_departement": 24}
headers = {"accept": "application/json"}

response = requests.get(url, params=params, headers=headers)
response.raise_for_status() 

data = response.json()
df = pd.DataFrame(data["data"])

print(data.get("count"), "résultats au total")
display(df.describe())
display(df.head())

234 résultats au total

                x           y  nb_mesures_piezo  profondeur_investigation
count  234.000000  234.000000        234.000000                228.000000
mean     0.688151   45.042011       1734.965812                166.714035
std      0.321903    0.246209       2663.643967                155.380297
min      0.016523   44.588493          0.000000                  0.000000
25%      0.419140   44.843795          1.000000                 58.125000
50%      0.690197   45.006581         14.500000                111.000000
75%      0.926058   45.224775       3868.750000                245.750000
max      1.388338   45.672371       8301.000000                800.000000

,code_bss,urn_bss,date_debut_mesure,date_fin_mesure,code_commune_insee,nom_commune,x,y,codes_bdlisa,urns_bdlisa,...,altitude_station,nb_mesures_piezo,code_departement,nom_departement,libelle_pe,profondeur_investigation,codes_masse_eau_edl,noms_masse_eau_edl,urns_masse_eau_edl,date_maj
0,08081X0026/SE.20,http://services.ades.eaufrance.fr/pointeau/080...,1996-09-05,2026-07-14,24255,Marquay,1.148945,44.923232,[348AA01],[http://reseau.eaufrance.fr/geotraitements/bdl...,...,154.0,7959,24,Dordogne,COMBE BOYER (MARQUAY - 24),87.0,[FG108],"[Calcaires, calcaires crayeux, grès, sables et...",[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,Tue Mar 18 21:37:09 CET 2025
1,07598X0005/A81,http://services.ades.eaufrance.fr/pointeau/075...,1996-07-30,2026-07-13,24555,Tourtoirac,1.070420,45.249720,[358AE07],[http://reseau.eaufrance.fr/geotraitements/bdl...,...,165.8,7212,24,Dordogne,ROUGERIE A81 (TOURTOIRAC-24),66.0,[FG003],[Calcaires du Jurassique moyen des bassins ver...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,Tue Sep 03 07:12:40 CEST 2024
2,07847X0010/F1,http://services.ades.eaufrance.fr/pointeau/078...,1986-10-01,1986-12-10,24085,La Cassagne,1.318102,45.045604,[358AE07],[http://reseau.eaufrance.fr/geotraitements/bdl...,...,156.87,3,24,Dordogne,F1,200.0,[FG040],[Calcaires du Jurassique moyen des Causses du ...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,Fri Jun 28 07:31:38 CEST 2024
3,07345X0020/F1,http://services.ades.eaufrance.fr/pointeau/073...,2002-07-11,2012-04-04,24119,Cherval,0.403764,45.376158,None,[],...,148.0,566,24,Dordogne,LA FEUILLADE (CHERVAL-24),135.0,[FG073A],[Multicouches calcaire captif du Turonien-Coni...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,Fri Jun 28 07:31:38 CEST 2024
4,07818X0030/F1,http://services.ades.eaufrance.fr/pointeau/078...,1996-08-30,1996-08-30,24462,Saint-Médard-de-Mussidan,0.332473,45.023305,None,[],...,57.0,1,24,Dordogne,NaN,70.0,None,None,[],Fri Jun 28 07:31:38 CEST 2024

### Piezometre

In [7]:
url = "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques"
headers = {"accept": "application/json"}

df_p= []

for i, code in enumerate(df["code_bss"]):
    params = {"size": 5000, "code_bss": code}

    response = requests.get(url, params=params, headers=headers)
    response.raise_for_status() 
    data = response.json()
    df_cache = pd.DataFrame(data["data"])

    df_p.append(df_cache)

    if i> 10 :
        break

piezometre_df = pd.concat(df_p, ignore_index=True)

print(len(piezometre_df), "résultats au total")

date_debut= piezometre_df['date_mesure'].min()
date_fin= piezometre_df['date_mesure'].max()

print(f"Début de la mesure {date_debut}, fin de la mesure {date_fin}")
print("\n")

21719 résultats au total
Début de la mesure 1981-03-26, fin de la mesure 2026-07-14